# Generated by Django 5.2.7 on 2025-10-14 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('assignment', 'Assignment'), ('fee', 'Fee'), ('result', 'Result'), ('attendance', 'Attendance'), ('event', 'Event'), ('promotion', 'Promotion'), ('system', 'System')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
