# Generated by Django 5.2.7 on 2026-04-27 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_requestpasswordreset_token_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOnboardingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('contact_full_name', models.CharField(max_length=150)),
                ('contact_role', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('school_size', models.CharField(blank=True, choices=[('1-100', '1-100 students'), ('101-300', '101-300 students'), ('301-700', '301-700 students'), ('700+', '700+ students')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('provisioned', 'Provisioned'), ('declined', 'Declined')], default='new', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_requests', to='account.package')),
                ('provisioned_school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_request', to='account.school')),
            ],
            options={
                'verbose_name': 'School Onboarding Request',
                'verbose_name_plural': 'School Onboarding Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
