# Generated by Django 5.2.7 on 2026-05-08 01:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_seed_default_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='change_reason',
            field=models.CharField(blank=True, help_text='e.g., Initial Signup, Renewal, Plan Upgrade', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student_class',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], help_text='Select the class this assignment is for', max_length=50),
        ),
        migrations.AlterField(
            model_name='promotionhistory',
            name='from_class',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='promotionhistory',
            name='to_class',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_class',
            field=models.CharField(blank=True, choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='promoted_to',
            field=models.CharField(blank=True, choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], help_text='Class to which student will be promoted', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='student_class',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=50),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.school')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='account.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_record', to='account.transaction'),
        ),
    ]
