# Generated by Django 5.2.7 on 2026-05-08 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_subscriptionhistory_change_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fees',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Fee', 'verbose_name_plural': 'Student Fees'},
        ),
        migrations.RemoveField(
            model_name='fees',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='paid',
        ),
        migrations.AddField(
            model_name='fees',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount actually paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='fees',
            name='amount_required',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount expected', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='student_class',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], default='JHS_1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='term',
            field=models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], default='TERM_1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fees',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition Fee'), ('admission', 'Admission Fee'), ('exam', 'Exam Fee'), ('transport', 'Transport Fee'), ('library', 'Library Fee'), ('sports', 'Sports Fee'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fees',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='account.student'),
        ),
        migrations.CreateModel(
            name='ClassFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_class', models.CharField(blank=True, choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN_1', 'Kindergarten 1'), ('KINDERGARTEN_2', 'Kindergarten 2'), ('UPPER_PRIMARY_1', 'Upper Primary 1'), ('UPPER_PRIMARY_2', 'Upper Primary 2'), ('UPPER_PRIMARY_3', 'Upper Primary 3'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], max_length=50, null=True)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('admission', 'Admission Fee'), ('exam', 'Exam Fee'), ('transport', 'Transport Fee'), ('library', 'Library Fee'), ('sports', 'Sports Fee'), ('other', 'Other')], default='tuition', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_year', models.CharField(help_text='e.g., 2025/2026', max_length=20)),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3')], max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_structures', to='account.school')),
            ],
            options={
                'verbose_name': 'Class Fee Structure',
                'verbose_name_plural': 'Class Fee Structures',
                'unique_together': {('school', 'student_class', 'fee_type', 'academic_year', 'term')},
            },
        ),
        migrations.AddField(
            model_name='fees',
            name='fee_structure',
            field=models.ForeignKey(blank=True, help_text='Link to the standard class fee structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to='account.classfee'),
        ),
    ]
