# Generated by Django 5.2.7 on 2026-06-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_fees_options_remove_fees_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_class',
            field=models.CharField(blank=True, choices=[('CRECHE', 'Creche'), ('NURSERY_1', 'Nursery 1'), ('NURSERY_2', 'Nursery 2'), ('KINDERGARTEN', 'Kindergarten'), ('UPPER_PRIMARY_4', 'Upper Primary 4'), ('UPPER_PRIMARY_5', 'Upper Primary 5'), ('UPPER_PRIMARY_6', 'Upper Primary 6'), ('JHS_1', 'JHS 1'), ('JHS_2', 'JHS 2'), ('JHS_3', 'JHS 3')], help_text='Class this teacher is responsible for taking attendance.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
