app = "klumus-tech-1"
primary_region = "ams"
console_command = "python manage.py shell"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8080"
  APP_ENV = "production"
  # You MUST set this in your Fly Secrets or here if you have a URL
  # Example: REDIS_URL = "redis://default:password@your-redis-url.upstash.io:6379"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[processes]
  # FORCED TO 8080 TO MATCH FLY.IO
  app = "gunicorn config.wsgi:application --bind 0.0.0.0:8080 --config gunicorn.conf.py"
  celery = "celery -A config worker --loglevel=INFO"

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"

[[statics]]
  guest_path = "/app/media"
  url_prefix = "/media/"

[[mounts]]
  source = "klumus_media"
  destination = "/app/media"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
