# Generated by Django 5.2.7 on 2025-10-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_grade', models.CharField(max_length=2)),
                ('risk_level', models.CharField(choices=[('High', 'High Risk'), ('Medium', 'Medium Risk'), ('Low', 'Low Risk')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
